travis:
  secure:
    BINSTAR_TOKEN: SWdxEomTJlclCItYAkoeKsYEfnG1inXw+FLq1lWW64cJa6NfcXh6WghJ0RedpzNODvoFhn5BSrtXDsmKFrqmvZ3I/ihDQBzh2aFof4D/sZBWBFtzowibsZ7NDrjUKFmUS1SF5qoOQE1RrtPnUBc67zpXQGaOjIihQrIxil3UyHfhEZYq177fht2e1jfs0p33CQYnZLOlZpd6yn56KI5C0wDhJ0/ANZrr4RSls3Lzhd9eXeDvqQXOgm3MX5S7+otGygau0FXU8h2LudP21wHJZyew2Auk/KEnn3jzZr2Xuug5hlIBCKle3pdzenpZJtS4NfcKhLMWOqmQ6xN+JEIGfOmLDOtxXJzB1FhHVGGJrFYUTnLCMDkkNH+QmvefA0UoJPEggf8K9vdJ1sBs0zgECGyOm7B5DfkIHdRlB1PgKtyeMq/5ojCuSr4mj7Zp0paOfGvgU9RiiekxIv+fHPe263PY0Y0STYp99gqIo4gn8bIgDPNm2NHvLmQklM1RKAkcWO+l0D83g3R/svpBOifL435Yulbyq6Y90n1ZNOCZyCS1nONXpZII3UAGAu/Iiy+P4FMeDMOrm+CSkqLxZhphoswBYdt4abyG5jdFYHEm8zCK23mFdjMwpdaxjjJrSgaVCozDiarHKQ7PHenSg3z5bt4StocNPkYWs+KwQT+EHwU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
